services:
  - type: web
    name: property-report-generator
    env: python
    buildCommand: chmod +x build.sh && ./build.sh && pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: LD_LIBRARY_PATH
        value: /usr/local/lib:/usr/lib
      - key: PYTHONPATH
        value: /usr/local/lib/python3.9/site-packages
    healthCheckPath: /